### ISSUE TITLE
Plasma samples not imported from Inform

### ISSUE THREAD

**Issue by binderal** [lachlancoin/euclids-database#4]
Although EDTA, PAX and serum samples have been successfully imported from Inform, plasma samples seem to have been systematically NOT been imported at all (this applies to "samples" as well as "surplus samples"). At least number, volume, pellet yes/no, and temperature have not been imported, the site samples are kept in ("Kept in site") seems to have made it into RedCap.
Examples: 201-1100, 201-1307, 201-0029, 201-1343.

**Comment by Miriam-Cebey** [comment]
Inform has a problem with plasma data and this data do not download with the rest of the information. It is possible to download it, but in a different way and is difficult to process it. It will be difficult to import this to Redcap, and it is an Inform problem. We were talking with them and they found no solution. I will try it again.
This is an example of the file: 
[plasmas.xlsx](https://github.com/lachlancoin/euclids-database/files/519428/plasmas.xlsx)

**Comment by Miriam-Cebey** [comment]
Is it possible to export the data from an xls or csv file to Redcap? Now they are not going to be modified and we can work with the data and export it once to have the plasma information in Redcap.
